config/routes.rb
Rails.application.routes.draw do
  get "inertia-example", to: "inertia_example#index"
  get "login", to: "application#login", as: :login

  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations"
  }


  # resources :chat_rooms

  resources :users
  resources :chat_rooms do
    resources :messages
  end
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "application#home"
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  belongs_to :user

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  use_inertia_instance_props
  def index
    @chat_rooms = ChatRoom.all.map do |chat_room|
      {
        id: chat_room.id,
        name: chat_room.name,
        user_id: chat_room.user_id,
        joined: chat_room.messages.any? { |message| message.user_id == current_user.id }
      }
    end

    render inertia: "ChatRooms/ChatRooms"
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    @messages = @chat_room.messages.includes(:user).map do |message|
      {
        id: message.id,
        content: message.content,
        chat_room_id: message.chat_room_id,
        user: {
          id: message.user.id,
          user_name: message.user.user_name,
          avatar: message.user.avatar.attached? ? url_for(message.user.avatar) : nil
        }
      }
    end

    render inertia: "ChatRooms/ChatRoom"
  end

  def new
    render inertia: "ChatRooms/New"
  end

  def create
    @chat_room = current_user.created_chat_rooms.new(chat_room_params)

    if @chat_room.save
      redirect_to chat_room_path(@chat_room), notice: "Chat room was successfully created."
    else
      render :new, alert: "Error creating chat room."
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:name)
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_new_message.html.erb
<%# app/views/chat_rooms/_new_message.html.erb %>

<%= form_with(model: [@chat_room, Message.new], local: true, html: { class: "new-message-form" }) do |f| %>
  <div class="field">
    <%= f.text_area :content,
                    rows: 1,
                    placeholder: "Type a message...",
                    autofocus: true,
                    class: "form-control message-input",
                    aria: { label: "Message" } %>
  </div>

  <div class="actions">
    <%= f.submit "Send", class: "btn btn-primary", data: { disable_with: "Sending..." } %>
  </div>
<% end %>

app/views/chat_rooms/index.html.erb
<ul>
  <% @chat_rooms.each do |room| %>
    <li><%=room.name %></li>
  <% end %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Create a new Chat Room</h1>

<%= form_with(model: @chat_room, url: chat_rooms_path, local: true) do |f| %>
  <% if @chat_room && @chat_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat_room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul>
        <% @chat_room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true, required: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create Room" %>
    <%= link_to "Back", chat_rooms_path %>
  </div>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.name %></h1>
<ul>
  <% @messages.each do |m| %>
    <li><%= m.content %> - <%= m.user.user_name %></li>
  <% end %>
</ul>

<%= render 'new_message' %>